language: node_js
node_js:
  - 'v7.0.0'
before_script:
#  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'grunt -f -v'
  #- sleep 2
  #- 'grunt serve'
after_script:
  - cat coverage/**/lcov.info | codeclimate
addons:
  code_climate:
    repo_token: 0c38fe0d4c6cc50053304b8cd4859d74624619e2707280ac9287be548e905404
