language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
#  - 'sudo sh ./bin/db.sh'
#  - sleep 3
  - 'grunt test'
#  - sleep 3
deploy:
  provider: heroku
  api_key: '6ac65b88-dd6d-421f-9fc7-c9ae18f71cb4'
  on:
    all_branches: true
run:
  - "grunt build"
  - "npm start"